#
# This file contains configuration flags to customize your site
#

# Name and description of your site (displayed in the header)
name: Marcela Bomfim
description: "Eu sou Desenvolvedora Web, com conhecimentos em Front-End e PHP, que ama o que faz e que quer passar um pouquinho desse amor para vocês."


#
# Flags below are optional
#

# Includes an icon in the header and footer for each username you enter
footer-links:
  dribbble:
  email: mbomfim@live.com
  facebook:
  flickr:
  github: marcelabomfim
  instagram:
  linkedin: marcelabomfim
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: cecelabomfim
  stackoverflow: # your stackoverflow profile, e.g. "users/3807565/akshay"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: blog-marcelabomfim

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-93065603-1

# Your website URL (e.g. http://akshayagarwal007.github.io)
# Used for Sitemap.xml and your RSS feed
url: http://marcelabomfim.github.io

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: "/blog"

# Full URL = url + baseurl
domain_name: http://marcelabomfim.github.io/blog


# Add this on each post to define excerpt
excerpt_separator: "<!-- more -->"

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
